### ISSUE TITLE
[1.16.4] Cant connect to a server that has Powah mod.

### ISSUE THREAD

**Issue by poswar** [JDKDigital/productive-bees#132]
**Summary**
Client user cant connect to a server that has Powah mod installed. Error: "_lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException_"

**Modpack Configuration**
  [✔️] Lollipop-1.16.4-3.2.3
  [✔️] Powah-1.16.4-2.3.6
  [✔️] productivebees-1.16.4-0.5.2.3
  [✔️] Forge 35.1.13
  [✔️] LWJGL 3.2.2
  [✔️] Minecraft 1.16.4

**Server-side stack-trace**
```
[15:49:14] [Netty Server IO #3/ERROR] [cy.jd.pr.ProductiveBees/]: Error writing bee conversion recipe to packet. productivebees:bee_conversion/uraninite_bee
java.lang.NullPointerException: null
	at cy.jdkdigital.productivebees.recipe.BeeConversionRecipe$Serializer.write(BeeConversionRecipe.java:141) ~[productivebees:1.16.4-0.5.2.3] {re:classloading}
	at cy.jdkdigital.productivebees.recipe.BeeConversionRecipe$Serializer.func_199427_a_(BeeConversionRecipe.java:98) ~[productivebees:1.16.4-0.5.2.3] {re:classloading}
	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_218771_a(SourceFile:64) ~[?:?] {re:classloading}
	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_148840_b(SourceFile:43) ~[?:?] {re:classloading}
	at net.minecraft.network.NettyPacketEncoder.encode(SourceFile:46) ~[?:?] {re:classloading}
	at net.minecraft.network.NettyPacketEncoder.encode(SourceFile:15) ~[?:?] {re:classloading}
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071) ~[netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300) ~[netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	at net.minecraft.network.NetworkManager.lambda$dispatchPacket$5(NetworkManager.java:196) ~[?:?] {re:classloading}
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465) [netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275] {}
[15:49:14] [Netty Server IO #3/ERROR] [minecraft/NettyPacketEncoder]: java.lang.NullPointerException
[15:49:14] [Server thread/INFO] [minecraft/ServerPlayNetHandler]: poswar lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException

```

**Comment by JaisDK** [comment]
Do you have uranium on the server? I'm guessing this is the problem. The uraninite bee is made from a uranium bee, but if it's not available it will throw an error.
I'll get that fixed and upload a new version where it's not depending on uranium.

**Comment by poswar** [comment]
The Powah mod adds some weird type of uranium. Maybe thats the problem

**Comment by JaisDK** [comment]
It's uraninite, it's not tagged as the same as uranium. Uranium can come from Mekanism

**Comment by poswar** [comment]
No uranium on the server. Only Uraninite

**Comment by JaisDK** [comment]
I put out a new version where it should be fixed

**Comment by poswar** [comment]
I just tested the last version (0.5.2.4). Now I can connect to the server! Thank You :D

**Comment by JaisDK** [comment]
awesome :)
