### ISSUE TITLE
Server Issue

### ISSUE THREAD

**Issue by WenXin20** [JDKDigital/productive-bees#136]
`Minecraft v1.16.4`
`Forge v35.1.28`
`Productive Bees v0.5.2.7`

After updating, I get an error when trying to connect to my server. The previous version, v0.5.2.5, worked fine.
<details>
  <summary>Error (Click Here)</summary>
  
  ```javascript[18:42:11] [Render thread/INFO]: Tags Loaded
[18:42:11] [Netty Client IO #6/ERROR]: Error reading beehive produce recipe from packet. productivebees:bee_produce/sulfur_bee
io.netty.handler.codec.EncoderException: java.io.UTFDataFormatException: malformed input around byte 79
	at net.minecraft.network.PacketBuffer.func_244272_a(PacketBuffer.java:410) ~[?:?]
	at net.minecraft.network.PacketBuffer.func_150793_b(PacketBuffer.java:381) ~[?:?]
	at net.minecraft.network.PacketBuffer.func_150791_c(PacketBuffer.java:476) ~[?:?]
	at net.minecraft.item.crafting.Ingredient.lambda$read$9(Ingredient.java:183) ~[?:?]
	at net.minecraft.item.crafting.Ingredient$$Lambda$27239/868025514.get(Unknown Source) ~[?:?]
	at java.util.stream.StreamSpliterators$InfiniteSupplyingSpliterator$OfRef.tryAdvance(StreamSpliterators.java:1356) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:576) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:255) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:438) ~[?:1.8.0_51]
	at net.minecraft.item.crafting.Ingredient.<init>(Ingredient.java:44) ~[?:?]
	at net.minecraft.item.crafting.Ingredient.func_209357_a(Ingredient.java:153) ~[?:?]
	at net.minecraft.item.crafting.Ingredient.func_199566_b(Ingredient.java:182) ~[?:?]
	at cy.jdkdigital.productivebees.recipe.AdvancedBeehiveRecipe$Serializer.lambda$read$1(AdvancedBeehiveRecipe.java:160) ~[?:1.16.4-0.5.2.7]
	at cy.jdkdigital.productivebees.recipe.AdvancedBeehiveRecipe$Serializer$$Lambda$27774/1005686145.accept(Unknown Source) ~[?:?]
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110) ~[?:1.8.0_51]
	at java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:557) ~[?:1.8.0_51]
	at cy.jdkdigital.productivebees.recipe.AdvancedBeehiveRecipe$Serializer.read(AdvancedBeehiveRecipe.java:159) [?:1.16.4-0.5.2.7]
	at cy.jdkdigital.productivebees.recipe.AdvancedBeehiveRecipe$Serializer.func_199426_a_(AdvancedBeehiveRecipe.java:115) [?:1.16.4-0.5.2.7]
	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_218772_c(SourceFile:57) [?:?]
	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_148837_a(SourceFile:35) [?:?]
	at net.minecraft.network.NettyPacketDecoder.decode(SourceFile:40) [?:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.io.UTFDataFormatException: malformed input around byte 79
	at java.io.DataInputStream.readUTF(DataInputStream.java:656) ~[?:1.8.0_51]
	at io.netty.buffer.ByteBufInputStream.readUTF(ByteBufInputStream.java:287) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at net.minecraft.nbt.CompressedStreamTools.func_152455_a(CompressedStreamTools.java:113) ~[?:?]
	at net.minecraft.nbt.CompressedStreamTools.func_152456_a(CompressedStreamTools.java:87) ~[?:?]
	at net.minecraft.network.PacketBuffer.func_244272_a(PacketBuffer.java:406) ~[?:?]
	... 61 more
  ```
  
</details>

**Comment by JaisDK** [comment]
Which mod is providing the sulfur?

**Comment by WenXin20** [comment]
It looks to be the [Eidolon](https://www.curseforge.com/minecraft/mc-mods/eidolon) mod.

**Comment by JaisDK** [comment]
I made a mistake with the sulfur bee requirements it seems. Does this one work for you?

[productivebees-1.16.4-0.5.2.7.zip](https://github.com/JDKDigital/productive-bees/files/5773748/productivebees-1.16.4-0.5.2.7.zip)

**Comment by MythicalMontie** [comment]
I'm not the OP but this file worked perfectly for me!

**Comment by JaisDK** [comment]
I uploaded the new file

**Comment by WenXin20** [comment]
Yep, works great. :)
