### ISSUE TITLE
Server Connection Issue

### ISSUE THREAD

**Issue by WenXin20** [JDKDigital/productive-bees#158]
`Minecraft v1.16.5`
`Forge v36.0.13`
`Productive Beees v0.6.3`

Upon trying to connect to my server, my client gets the following error:
<details>
  <summary>Log Error (Click Here)</summary>
  
  ```javascript[06Feb2021 18:06:49.963] [Netty Epoll Server IO #2/FATAL] [net.minecraftforge.fml.loading.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/world/ClientWorld for invalid dist DEDICATED_SERVER
[06Feb2021 18:06:49.971] [Netty Epoll Server IO #2/ERROR] [cy.jdkdigital.productivebees.ProductiveBees/]: Error writing beehive produce recipe to packet. productivebees:bee_produce/fluids/chocolate_bee
java.lang.RuntimeException: Attempted to load class net/minecraft/client/world/ClientWorld for invalid dist DEDICATED_SERVER
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[forge-1.16.5-36.0.7.jar:36.0]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_265]
	at cy.jdkdigital.productivebees.integrations.jei.ingredients.BeeIngredientFactory.createList(BeeIngredientFactory.java:46) ~[productivebees:1.16.5-0.6.3]
	at cy.jdkdigital.productivebees.integrations.jei.ingredients.BeeIngredientFactory.getOrCreateList(BeeIngredientFactory.java:36) ~[productivebees:1.16.5-0.6.3]
	at cy.jdkdigital.productivebees.integrations.jei.ingredients.BeeIngredientFactory.lambda$getIngredient$0(BeeIngredientFactory.java:40) ~[productivebees:1.16.5-0.6.3]
	at net.minecraftforge.common.util.Lazy$Fast.get(Lazy.java:69) ~[forge:?]
	at cy.jdkdigital.productivebees.recipe.AdvancedBeehiveRecipe$Serializer.write(AdvancedBeehiveRecipe.java:172) ~[productivebees:1.16.5-0.6.3]
	at cy.jdkdigital.productivebees.recipe.AdvancedBeehiveRecipe$Serializer.func_199427_a_(AdvancedBeehiveRecipe.java:115) ~[productivebees:1.16.5-0.6.3]
	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_218771_a(SourceFile:64) ~[?:?]
	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_148840_b(SourceFile:43) ~[?:?]
	at net.minecraft.network.NettyPacketEncoder.encode(SourceFile:46) ~[?:?]
	at net.minecraft.network.NettyPacketEncoder.encode(SourceFile:15) ~[?:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[server-1.16.5-20210115.111550-extra.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[server-1.16.5-20210115.111550-extra.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[server-1.16.5-20210115.111550-extra.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[server-1.16.5-20210115.111550-extra.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[server-1.16.5-20210115.111550-extra.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[server-1.16.5-20210115.111550-extra.jar:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071) ~[server-1.16.5-20210115.111550-extra.jar:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300) ~[server-1.16.5-20210115.111550-extra.jar:?]
	at net.minecraft.network.NetworkManager.lambda$dispatchPacket$5(NetworkManager.java:196) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [server-1.16.5-20210115.111550-extra.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [server-1.16.5-20210115.111550-extra.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313) [server-1.16.5-20210115.111550-extra.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [server-1.16.5-20210115.111550-extra.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
[06Feb2021 18:06:49.983] [Netty Epoll Server IO #2/ERROR] [net.minecraft.network.NettyPacketEncoder/]: java.lang.RuntimeException: Attempted to load class net/minecraft/client/world/ClientWorld for invalid dist DEDICATED_SERVER
[06Feb2021 18:06:50.071] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: WenXin2 joined the game
[06Feb2021 18:06:50.339] [Server thread/INFO] [STDOUT/]: [com.wuest.prefab.Events.ModEventHandler:onPlayerLoginEvent:49]: Sent config to 'WenXin2'.
[06Feb2021 18:06:50.339] [Server thread/INFO] [Waila/]: Syncing config to WenXin2 (eb83f5a3-397a-4e14-80bc-914ff91890f0)
[06Feb2021 18:06:50.356] [Server thread/INFO] [antiqueatlas/]: Sent markers data #-1 to player WenXin2
[06Feb2021 18:06:50.357] [Server thread/INFO] [antiqueatlas/]: Sent custom biome data to player WenXin2
[06Feb2021 18:06:50.357] [Server thread/INFO] [antiqueatlas/]: Sent custom biome data to player WenXin2
[06Feb2021 18:06:50.357] [Server thread/INFO] [antiqueatlas/]: Sent custom biome data to player WenXin2
[06Feb2021 18:06:50.357] [Server thread/INFO] [antiqueatlas/]: Sent custom biome data to player WenXin2
[06Feb2021 18:06:50.357] [Server thread/INFO] [antiqueatlas/]: Sent custom biome data to player WenXin2
[06Feb2021 18:06:50.357] [Server thread/INFO] [antiqueatlas/]: Sent custom biome data to player WenXin2
[06Feb2021 18:06:50.357] [Server thread/INFO] [antiqueatlas/]: Sent custom biome data to player WenXin2
[06Feb2021 18:06:50.357] [Server thread/INFO] [antiqueatlas/]: Sent custom biome data to player WenXin2
[06Feb2021 18:06:50.357] [Server thread/INFO] [antiqueatlas/]: Sent custom biome data to player WenXin2
[06Feb2021 18:06:50.357] [Server thread/INFO] [antiqueatlas/]: Sent custom biome data to player WenXin2
[06Feb2021 18:06:50.357] [Server thread/INFO] [antiqueatlas/]: Sent custom biome data to player WenXin2
[06Feb2021 18:06:50.357] [Server thread/INFO] [antiqueatlas/]: Sent custom biome data to player WenXin2
[06Feb2021 18:06:50.357] [Server thread/INFO] [antiqueatlas/]: Sent custom biome data to player WenXin2
[06Feb2021 18:06:50.357] [Server thread/INFO] [antiqueatlas/]: Sent custom biome data to player WenXin2
[06Feb2021 18:06:50.358] [Server thread/INFO] [antiqueatlas/]: Sent custom biome data to player WenXin2
[06Feb2021 18:06:50.358] [Server thread/INFO] [antiqueatlas/]: Sent custom biome data to player WenXin2
[06Feb2021 18:06:50.358] [Server thread/INFO] [antiqueatlas/]: Sent custom biome data to player WenXin2
[06Feb2021 18:06:50.389] [Server thread/INFO] [antiqueatlas/]: Sending dimension #ResourceKey[minecraft:dimension / minecraft:overworld]
[06Feb2021 18:06:50.391] [Server thread/INFO] [antiqueatlas/]: Sent dimension #ResourceKey[minecraft:dimension / minecraft:overworld] (14 tiles)
[06Feb2021 18:06:50.392] [Server thread/INFO] [antiqueatlas/]: Sent Atlas #-1419920888 data to player WenXin2
[06Feb2021 18:06:50.408] [Server thread/INFO] [structurize/]: New Server UUID db1acbd0-cf48-4769-888e-3ef16b7da1d5
[06Feb2021 18:06:50.832] [Server thread/WARN] [minecolonies/]: Splitting message: class com.minecolonies.coremod.network.messages.client.UpdateClientWithRecipesMessage it is too big to send normally. This message is only printed once
[06Feb2021 18:06:50.931] [Server thread/INFO] [Enigmatic Legacy/INFO]: Synchronizing omniconfig files to WenXin2...
[06Feb2021 18:06:50.931] [Server thread/INFO] [Enigmatic Legacy/INFO]: Sending data for enigmaticlegacy-common.omniconf
[06Feb2021 18:06:51.135] [Thread-47/INFO] [chancecubes/]: No custom rewards detected for the current user!
[06Feb2021 18:06:51.834] [Netty Epoll Server IO #3/ERROR] [net.minecraft.network.NettyPacketEncoder/]: io.netty.handler.codec.EncoderException: String too big (was 40174 bytes encoded, max 32767)
[06Feb2021 18:06:51.898] [Server thread/WARN] [net.minecraft.server.MinecraftServer/]: Can't keep up! Is the server overloaded? Running 4180ms or 83 ticks behind
[06Feb2021 18:06:51.964] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: WenXin2 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.RuntimeException: Attempted to load class net/minecraft/client/world/ClientWorld for invalid dist DEDICATED_SERVER
[06Feb2021 18:06:51.964] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: WenXin2 left the game
  ```
  
</details>

![2021-02-06_12 12 14](https://user-images.githubusercontent.com/12000593/107126641-af375200-6876-11eb-881a-52b28bc979f9.png)

**Comment by JaisDK** [comment]
New version out, does it fix your issue?

**Comment by WenXin20** [comment]
Yep that one is working so far.
