### ISSUE TITLE
Bee capture crash

### ISSUE THREAD

**Issue by joklbash** [JDKDigital/productive-bees#160]
When I attempted to capture a neon cuckoo bee, the server crashed with the below error. Is this version of production bees still 1.16.4 compartible? I couldn't get GD Launcher to detect the update, so I manually loaded, which made me think it wasn't really marked as version compatible for what I was trying to load it in.

java.lang.NoSuchMethodError: net.minecraft.entity.player.PlayerInventory.func_184429_b(Lnet/minecraft/item/ItemStack;)I
	at cy.jdkdigital.productivebees.common.item.BeeCage.func_111207_a(BeeCage.java:92) ~[productivebees:1.16.5-0.6.4]
	at net.minecraft.item.ItemStack.func_111282_a_(ItemStack.java:338) ~[?:?]
	at net.minecraft.entity.player.PlayerEntity.func_190775_a(PlayerEntity.java:956) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147340_a(ServerPlayNetHandler.java:1194) ~[?:?]
	at net.minecraft.network.play.client.CUseEntityPacket.func_148833_a(SourceFile:74) ~[?:?]
	at net.minecraft.network.play.client.CUseEntityPacket.func_148833_a(SourceFile:13) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:733) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:716) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:710) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:696) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:645) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]

**Comment by JaisDK** [comment]
It's a beta version that's why GDL doesn't show it to you unless you tell it to get beta version. Which version exactly are you using?

**Comment by joklbash** [comment]
Using 1.16.5-0.6.4. I've got a new world and just started out. I was able to capture Mason and a few others without issue. Maybe lucky on those.

**Comment by JaisDK** [comment]
I have some changes to the BeeCage in dev, I'll upload those. It could be something that happens if you have only 1 cage in the stack, this is what I was working on fixing.

**Comment by joklbash** [comment]
Cool, I was down to 1 cage when it happened. I can test and let you know.

**Comment by JaisDK** [comment]
Uploaded it now. Hopefully it works as I don't have much time today for testing it.

**Comment by joklbash** [comment]
That patch looks to have resolved the issue with a single cage in hand.

BTW, on the beta not showing in GDL, I've got it set of alphas since a lot of mods stay in perpetual alpha/beta state. I don't have any issues seeing the 0.6.2 or 0.6.3 beta versions. Just 0.6.4 and 0.6.5 stopped showing up.

Thanks for the fix.
