### ISSUE TITLE
[1.16.5] v0.6.9.5 Sever connection issue related to Powah and bee conversion

### ISSUE THREAD

**Issue by SchwiftyGeez** [JDKDigital/productive-bees#175]
I'm playing the TNP Limitless 3 pack and having a server connection error when attempting to connect to the server. Powah mod version is 2.3.16.

`[Netty Server IO #1/ERROR] [cy.jdkdigital.productivebees.ProductiveBees/]: Error writing bee conversion recipe to packet. productivebees:bee_conversion/powah/uraninite_bee
java.lang.NullPointerException: null
	at cy.jdkdigital.productivebees.recipe.BeeConversionRecipe$Serializer.write(BeeConversionRecipe.java:141) ~[productivebees:1.16.5-0.6.9.5]
	at cy.jdkdigital.productivebees.recipe.BeeConversionRecipe$Serializer.func_199427_a_(BeeConversionRecipe.java:98) ~[productivebees:1.16.5-0.6.9.5]
	at malte0811.recipebuffers.impl.RecipeListSerializer.writeRecipe(RecipeListSerializer.java:187) ~[recipebuffers:2.1]
	at malte0811.recipebuffers.impl.RecipeListSerializer.writeRecipes(RecipeListSerializer.java:78) ~[recipebuffers:2.1]
	at malte0811.recipebuffers.impl.NewRecipePacket.writePacketData(NewRecipePacket.java:50) ~[recipebuffers:2.1]
	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_148840_b(SourceFile:1041) ~[?:?]
	at net.minecraftforge.network.VanillaPacketSplitter.appendPackets(VanillaPacketSplitter.java:99) ~[forge:?]
	at net.minecraftforge.network.ForgeConnectionNetworkFilter.splitPacket(ForgeConnectionNetworkFilter.java:61) ~[forge:?]
	at net.minecraftforge.network.VanillaPacketFilter.encode(VanillaPacketFilter.java:75) ~[forge:?]
	at net.minecraftforge.network.VanillaPacketFilter.encode(VanillaPacketFilter.java:38) ~[forge:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88) ~[server-1.16.5-20210115.111550-extra.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[server-1.16.5-20210115.111550-extra.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[server-1.16.5-20210115.111550-extra.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[server-1.16.5-20210115.111550-extra.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[server-1.16.5-20210115.111550-extra.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[server-1.16.5-20210115.111550-extra.jar:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071) ~[server-1.16.5-20210115.111550-extra.jar:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300) ~[server-1.16.5-20210115.111550-extra.jar:?]
	at net.minecraft.network.NetworkManager.lambda$sendPacket$5(NetworkManager.java:196) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [server-1.16.5-20210115.111550-extra.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [server-1.16.5-20210115.111550-extra.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465) [server-1.16.5-20210115.111550-extra.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [server-1.16.5-20210115.111550-extra.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]`
	
Removing Productive Bees from the client/server fixes the connection issue. I then tried saving the world without Productive Bees, re-adding it and restarting, but was met with the same connection error. I can provide more info, but I'm not sure what you would need. Just ask and I'll provide.

**Comment by JaisDK** [comment]
Does the pack have any uranium?

**Comment by SchwiftyGeez** [comment]
Yes it does, from Powah and I believe there was a uranium ore from another mod as well. But Powah's is called uranite I believe

**Comment by JaisDK** [comment]
I can see that Mekanism is in the pack, they add uranium.

Gonna load it up and see what I can find.

**Comment by SchwiftyGeez** [comment]
I loaded up the pack without Productive bees and I'm also seeing Uranium Ore from the Silent's Mechanisms mod

**Comment by JaisDK** [comment]
I loaded up a fresh server install with the latest version and I am not getting the error when connecting. Do you have any custom or old datapacks enabled?

**Comment by SchwiftyGeez** [comment]
I do have a few mods that I added, and one custom data pack:
 
 Added mods:
 - minecolonies v0.14.44
 - structurize v0.13.148
 - DoggyTalents v2.0.1.3
 - Dungeons_Plus v1.1.3
 - Structure_Gel v1.7.5
 - Valhelsia Structures v16.0.5
 
 Datapack:
 Repurposed Structures + Ice and Fire (link: https://github.com/TelepathicGrunt/RepurposedStructures/releases/tag/0.0.3 )
 
 Another thing that may be affecting this is I have been upgrading this world as new pack versions are released, starting at Limitless version 1.9.5.

**Comment by JaisDK** [comment]
Maybe they used to include a datapack for PB. Can you check the `kubejs\data` folder on the server and see if there's a productivebees folder? The newest version does not have one.

**Comment by SchwiftyGeez** [comment]
looking at the 1.9.6 and 1.9.5 versions but there doesn't seem to be a folder for productivebees there. looked in kubejs/data

**Comment by JaisDK** [comment]
I downloaded 1.9.7, but does your server have a productivebees folder? or anything related to productivebees in the world/datapacks folder?

**Comment by SchwiftyGeez** [comment]
nothing in world/datapacks, did a search for "productive" on the server root folder and there isn't anything in 1.9.7 that isn't in 1.9.6 besides a few sort-order files for JEI.

**Comment by JaisDK** [comment]
I don't know what it could be then, I can't reproduce it. This was an error I fixed back in March 6 version 0.6.9.

Are you having problems if you create a new world or do a fresh install?

**Comment by SchwiftyGeez** [comment]
Alright, no worries then, I'll try making a new world later tonight (currently just playing without bees) but don't really want to lose the progress I have on the world. If I have to play without the bee's that's fine, I'm sure I'll get to play with them in another modpack. Thanks for looking into it though, I appreciate it.

If you want to look into it more I can zip up my server and get it to you somehow. I'm not sure what else I can do to help track it down.

**Comment by JaisDK** [comment]
If you can zip it I can take a look

**Comment by SchwiftyGeez** [comment]
Sorry it took a while to respond, I've been away from my PC for a while. Here's the zipped server files: https://drive.google.com/file/d/1ZyuYveVGByAHgZyAmKLkwEm4S0_-5urn/view?usp=sharing

You'll also need to add these mods to the client: https://drive.google.com/file/d/1wgD0bO1oUDBKwN6HOhUSNN1VkIOiRpiW/view?usp=sharing

Let me know if you need anything else or if I missed something. One thing I noticed also about this server is that even once it's ready the client will still show "Unable to connect to server" in the server list. But it can still be joined just fine (provided that the server is actually ready).

**Comment by JaisDK** [comment]
Thank you, I'll download now and take a look when I find the time.

I know that the client will show incompatible mod list if you have client mods installed that are not on the server, like ReAuth in this pack.

**Comment by MokahTGS** [comment]
We are having this same issue.

**Comment by MokahTGS** [comment]
TNP Limitless 1.9.9b does have a Productive Bees folder in the Kubejs/data folder.  It is referencing Silent Mechanisms uranium dust.

https://pastebin.com/iX0rW6xc

**Comment by MokahTGS** [comment]
Our server log when the connection error happens: https://pastebin.com/WtW8Lh8u

**Comment by MokahTGS** [comment]
I just confirmed that this is still happing with productivebees-1.16.5-0.6.9.8.  Removing the mod allows us to join the server.

**Comment by JaisDK** [comment]
[productivebees-1.16.5-0.6.9.8.zip](https://github.com/JDKDigital/productive-bees/files/6259363/productivebees-1.16.5-0.6.9.8.zip)

Try this build, I've removed that recipe. If there are still problems, the world is caching the recipes in some ways.

**Comment by MokahTGS** [comment]
That seems to have fixed it, although the server browser still says that the client can't connect to the server.  You can just ignore that and load in anyway however.  Not sure if that is related or just some mixture of TNP Limitless 3 , added mods and bees.

**Comment by JaisDK** [comment]
Weird that it's working and weird that it wasn't become, but I won't complain :)

The server list will show as not working if you have client side mods installed, like ReAuth which are not present on the server. It can indeed just be ignore.

**Comment by MokahTGS** [comment]
Did you turn off all recipes?  Seems that no recipes are showing now.

**Comment by JaisDK** [comment]
I only remove one recipe. Is it all recipes in JEI or all PB recipes? Can I see a client log?

**Comment by MokahTGS** [comment]
All recipes

**Comment by JaisDK** [comment]
try increasing the `beeSyncDelay` config in the `world/serverconfig/productivebees-server.toml`

**Comment by MokahTGS** [comment]
So I've confirmed that it's PB that is causing all recipes to stop working with the new version you posted above.  Increasing the delay also does nothing.  I increased it to 100 in the config on the server.

**Comment by JaisDK** [comment]
I'll need some logs to look into, probably the client debug log will be most helpful

**Comment by MokahTGS** [comment]
https://www.dropbox.com/s/btni4v1hrismv71/logs.zip?dl=0

Logs from last try.

**Comment by JaisDK** [comment]
says the folder is empty

**Comment by MokahTGS** [comment]
https://www.dropbox.com/s/mreykkvb5vrai07/logs.zip?dl=0

Because I'm dumb...don't zip while game is open.

**Comment by JaisDK** [comment]
I blame windows for such things :)

Can I see the server log too?

The client log looks normal except for one thing:
```
[06Apr2021 17:21:42.249] [Render thread/ERROR] [cy.jdkdigital.productivebees.ProductiveBees/]: Error reading bee breeding recipe from packet. productivebees:bee_breeding/ingots/radioactive_bee
net.minecraft.util.ResourceLocationException: Non [a-z0-9_.-] character in namespace of location: ????=?productivebees:
```
Which does not make sense, the file is just fine. This error would however cause the powah recipe error you first saw.

**Comment by JaisDK** [comment]
It could make sense if the buffer I'm reading the bee ingredient from is not complete. Does the server log contain anything in the form of `Bee breeding recipe ingredient missing` or `Bee breeding recipe child missing`?

**Comment by JaisDK** [comment]
[productivebees-1.16.5-0.6.9.8_fix_radioactive.zip](https://github.com/JDKDigital/productive-bees/files/6267956/productivebees-1.16.5-0.6.9.8_fix_radioactive.zip)

This should either take care of the recipe problem or fail hard so it's more visible what the problem is.

**Comment by MokahTGS** [comment]
Server Logs
https://www.dropbox.com/s/ovafgtib66v79x5/logs.zip?dl=0

**Comment by JaisDK** [comment]
Thanks, there's a good chance the above version fixes it.

**Comment by MokahTGS** [comment]
That seems to have got it sorted.  Recipes are working as they should.

**Comment by JaisDK** [comment]
Sweet, I'll post that update tomorrow. Thanks for all the testing!

Do you have a Radioactive and a Uraninite bee now?

**Comment by MokahTGS** [comment]
Uraninite bee is there...no radioactive bee.
