### ISSUE TITLE
[1.16.5] [Crash] ItemStack value must not be empty.

### ISSUE THREAD

**Issue by hron84** [JDKDigital/productive-bees#178]
The whole SSP hangs up. 

```
java.lang.IllegalArgumentException: ItemStack value must not be empty. 1 air minecraft:air
        at mezz.jei.util.ErrorUtil.checkNotEmpty(ErrorUtil.java:184) ~[jei:7.6.1.75]
        at mezz.jei.plugins.vanilla.ingredients.item.ItemStackHelper.getUniqueId(ItemStackHelper.java:87) ~[jei:7.6.1.75]
        at mezz.jei.plugins.vanilla.ingredients.item.ItemStackHelper.getUniqueId(ItemStackHelper.java:28) ~[jei:7.6.1.75]
        at mezz.jei.recipes.RecipeMap.addRecipe(RecipeMap.java:94) ~[jei:7.6.1.75]
        at mezz.jei.recipes.RecipeMap.addRecipe(RecipeMap.java:75) ~[jei:7.6.1.75]
        at mezz.jei.recipes.RecipeManager.addRecipe(RecipeManager.java:144) ~[jei:7.6.1.75]
        at mezz.jei.recipes.RecipeManager.addRecipeTyped(RecipeManager.java:105) ~[jei:7.6.1.75]
        at mezz.jei.recipes.RecipeManager.addRecipes(RecipeManager.java:98) ~[jei:7.6.1.75]
        at mezz.jei.recipes.RecipeManager.<init>(RecipeManager.java:90) ~[jei:7.6.1.75]
        at mezz.jei.load.PluginLoader.getRecipeManager(PluginLoader.java:142) ~[jei:7.6.1.75]
        at mezz.jei.startup.JeiStarter.start(JeiStarter.java:73) ~[jei:7.6.1.75]
        at mezz.jei.startup.ClientLifecycleHandler.startJEI(ClientLifecycleHandler.java:141) ~[jei:7.6.1.75]
        at mezz.jei.startup.ClientLifecycleHandler.setupJEI(ClientLifecycleHandler.java:134) ~[jei:7.6.1.75]
        at mezz.jei.startup.ClientLifecycleHandler.lambda$new$2(ClientLifecycleHandler.java:100) ~[jei:7.6.1.75]
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?]
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
        at net.minecraftforge.client.ForgeHooksClient.onRecipesUpdated(ForgeHooksClient.java:706) ~[forge:?]
        at cy.jdkdigital.productivebees.network.packets.Messages$BeesMessage.lambda$handle$1(Messages.java:58) ~[productivebees:1.16.5-0.6.9.7]
        at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) ~[forge:?]
        at cy.jdkdigital.productivebees.network.packets.Messages$BeesMessage.handle(Messages.java:48) ~[productivebees:1.16.5-0.6.9.7]
        at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) ~[forge:?]
        at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_242]
        at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) ~[forge:?]
        at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[forge:?]
        at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[forge:?]
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?]
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
        at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:86) ~[forge:?]
        at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:90) ~[forge:?]
        at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_242]
        at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:90) ~[forge:?]
        at net.minecraft.client.network.play.ClientPlayNetHandler.func_147240_a(ClientPlayNetHandler.java:1904) ~[?:?]
        at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:59) ~[?:?]
        at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:11) ~[?:?]
        at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?]
        at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947) ~[?:?]
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?]
        at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
        at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.1.0.jar:36.1]
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
```
Minecraft 1.16.5
Forge: 36.1.0
ProductiveBees: 0.6.9.7

ModPack: Engineer's Life 2 (latest version)

I'll try to downgrade the mod.

**Comment by JaisDK** [comment]
Can you provide the full debug log please?

**Comment by hron84** [comment]
[debug-1.log](https://github.com/JDKDigital/productive-bees/files/6218631/debug-1.log)

**Comment by JaisDK** [comment]
There is nothing in there causing a hang, the error you postedis JEI complaining about invalid recipes. The reason you see PB in the stacktrace is because PB is forcing JEI to reindex recipes. If you scroll further up you see the errors repeated without PB in the trace.
