### ISSUE TITLE
Crash with Cooking for Blockheads

### ISSUE THREAD

**Issue by Partonetrain** [JDKDigital/productive-bees#19]
(I have lots of other mods, but CfB is the only mod in the stacktrace)
```
[11:13:50] [Server-Worker-19/INFO]: [net.minecraft.util.registry.Bootstrap:func_179870_a:103]: ---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 5/15/20 11:13 AM
Description: Feature placement

java.lang.NullPointerException: Feature placement
	at net.blay09.mods.cookingforblockheads.compat.CompatCapabilityLoader.attachTileEntityCapabilities(CompatCapabilityLoader.java:47) ~[?:8.0.1] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_87_CompatCapabilityLoader_attachTileEntityCapabilities_AttachCapabilitiesEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:564) ~[?:?] {re:mixin,re:classloading}
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:558) ~[?:?] {re:mixin,re:classloading}
	at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:48) ~[?:?] {re:mixin,re:classloading}
	at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:44) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.tileentity.TileEntity.<init>(TileEntity.java:34) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.tileentity.BeehiveTileEntity.<init>(SourceFile:62) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at cy.jdkdigital.productivebees.tileentity.AdvancedBeehiveTileEntityAbstract.<init>(AdvancedBeehiveTileEntityAbstract.java:48) ~[?:1.15.2-0.1.6] {re:classloading}
	at cy.jdkdigital.productivebees.tileentity.SolitaryNestTileEntity.<init>(SolitaryNestTileEntity.java:40) ~[?:1.15.2-0.1.6] {re:classloading}
	at cy.jdkdigital.productivebees.init.ModTileEntityTypes$$Lambda$8087/109394862.get(Unknown Source) ~[?:?] {}
	at net.minecraft.tileentity.TileEntityType.func_200968_a(TileEntityType.java:92) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:extratags.mixins.json:BlockEntityTypeMixin,pl:mixin:A}
	at cy.jdkdigital.productivebees.block.SolitaryNest.createTileEntity(SolitaryNest.java:58) ~[?:1.15.2-0.1.6] {re:classloading}
	at net.minecraftforge.common.extensions.IForgeBlockState.createTileEntity(IForgeBlockState.java:130) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.world.gen.WorldGenRegion.func_175625_s(WorldGenRegion.java:194) ~[?:?] {re:classloading}
	at cy.jdkdigital.productivebees.gen.feature.SolitaryNestFeature.placeNest(SolitaryNestFeature.java:81) ~[?:1.15.2-0.1.6] {re:classloading}
	at cy.jdkdigital.productivebees.gen.feature.WoodSolitaryNestFeature.place(WoodSolitaryNestFeature.java:60) ~[?:1.15.2-0.1.6] {re:classloading}
	at cy.jdkdigital.productivebees.gen.feature.WoodSolitaryNestFeature.func_212245_a(WoodSolitaryNestFeature.java:14) ~[?:1.15.2-0.1.6] {re:classloading}
	at net.minecraft.world.gen.feature.ConfiguredFeature.func_222734_a(SourceFile:53) ~[?:?] {re:classloading}
	at net.minecraft.world.biome.Biome.func_203608_a(Biome.java:281) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:extratags.mixins.json:BiomeMixin,pl:mixin:A}
	at net.minecraft.world.gen.ChunkGenerator.func_202092_b(ChunkGenerator.java:103) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.chunk.ChunkStatus.lambda$static$9(ChunkStatus.java:74) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.chunk.ChunkStatus$$Lambda$1615/1692009786.doWork(Unknown Source) ~[?:?] {}
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:195) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:519) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:world.chunk.ChunkManagerMixin,pl:mixin:A}
	at net.minecraft.world.server.ChunkManager$$Lambda$12504/429741161.apply(Unknown Source) ~[?:?] {}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-2.0.24.jar:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at net.minecraft.world.server.ChunkManager.lambda$func_223156_b$20(ChunkManager.java:517) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:world.chunk.ChunkManagerMixin,pl:mixin:A}
	at net.minecraft.world.server.ChunkManager$$Lambda$12489/178519170.apply(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51] {}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter$$Lambda$12502/993850346.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:83) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:123) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:91) ~[?:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server-Worker-19
Stacktrace:
	at net.blay09.mods.cookingforblockheads.compat.CompatCapabilityLoader.attachTileEntityCapabilities(CompatCapabilityLoader.java:47)
	at net.minecraftforge.eventbus.ASMEventHandler_87_CompatCapabilityLoader_attachTileEntityCapabilities_AttachCapabilitiesEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:564)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:558)
	at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:48)
	at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:44)
	at net.minecraft.tileentity.TileEntity.<init>(TileEntity.java:34)
	at net.minecraft.tileentity.BeehiveTileEntity.<init>(SourceFile:62)
	at cy.jdkdigital.productivebees.tileentity.AdvancedBeehiveTileEntityAbstract.<init>(AdvancedBeehiveTileEntityAbstract.java:48)
	at cy.jdkdigital.productivebees.tileentity.SolitaryNestTileEntity.<init>(SolitaryNestTileEntity.java:40)
	at cy.jdkdigital.productivebees.init.ModTileEntityTypes$$Lambda$8087/109394862.get(Unknown Source)
	at net.minecraft.tileentity.TileEntityType.func_200968_a(TileEntityType.java:92)
	at cy.jdkdigital.productivebees.block.SolitaryNest.createTileEntity(SolitaryNest.java:58)
	at net.minecraftforge.common.extensions.IForgeBlockState.createTileEntity(IForgeBlockState.java:130)
	at net.minecraft.world.gen.WorldGenRegion.func_175625_s(WorldGenRegion.java:194)
	at cy.jdkdigital.productivebees.gen.feature.SolitaryNestFeature.placeNest(SolitaryNestFeature.java:81)
	at cy.jdkdigital.productivebees.gen.feature.WoodSolitaryNestFeature.place(WoodSolitaryNestFeature.java:60)
	at cy.jdkdigital.productivebees.gen.feature.WoodSolitaryNestFeature.func_212245_a(WoodSolitaryNestFeature.java:14)
	at net.minecraft.world.gen.feature.ConfiguredFeature.func_222734_a(SourceFile:53)

-- Feature --
Details:
	Id: productivebees:oak_wood_nest_feature
	Description: cy.jdkdigital.productivebees.gen.feature.WoodSolitaryNestFeature@1efe2fb2
Stacktrace:
	at net.minecraft.world.biome.Biome.func_203608_a(Biome.java:281)

-- Generation --
Details:
	CenterX: -9
	CenterZ: 10
	Step: VEGETAL_DECORATION
	Seed: 6732929913277648253
	Biome: biomesoplenty:redwood_forest
Stacktrace:
	at net.minecraft.world.gen.ChunkGenerator.func_202092_b(ChunkGenerator.java:103)
	at net.minecraft.world.chunk.ChunkStatus.lambda$static$9(ChunkStatus.java:74)
	at net.minecraft.world.chunk.ChunkStatus$$Lambda$1615/1692009786.doWork(Unknown Source)
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:195)

-- Chunk to be generated --
Details:
	Location: -9,10
	Position hash: 47244640247
	Generator: biomesoplenty.common.world.ChunkGeneratorOverworldBOP@55487398
Stacktrace:
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:519)
	at net.minecraft.world.server.ChunkManager$$Lambda$12504/429741161.apply(Unknown Source)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.world.server.ChunkManager.lambda$func_223156_b$20(ChunkManager.java:517)
	at net.minecraft.world.server.ChunkManager$$Lambda$12489/178519170.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58)
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter$$Lambda$12502/993850346.run(Unknown Source)
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:83)
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:123)
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:91)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)


```
Full Log: 
[latest.log](https://github.com/JDKDigital/productive-bees/files/4635620/latest.log)

**Comment by JaisDK** [comment]
Fixed in 0.1.7
