### ISSUE TITLE
Parsing error loading recipe productivebees:ars_nouveau/arcane_bee

### ISSUE THREAD

**Issue by coldReactive** [JDKDigital/productive-bees#224]
```
[12:52:28] [Render thread/ERROR]: Parsing error loading recipe productivebees:ars_nouveau/arcane_bee
com.google.gson.JsonSyntaxException: Missing pedestalItems, expected to find a JsonArray
	at net.minecraft.util.GsonHelper.m_13933_(GsonHelper.java:432) ~[client-1.18.1-20211210.034407-srg.jar%23125!:?]
	at com.hollingsworth.arsnouveau.api.enchanting_apparatus.EnchantingApparatusRecipe$Serializer.fromJson(EnchantingApparatusRecipe.java:197) ~[ars_nouveau-1.18.1-2.0.2.jar%2355!:2.0.2]
	at com.hollingsworth.arsnouveau.api.enchanting_apparatus.EnchantingApparatusRecipe$Serializer.m_6729_(EnchantingApparatusRecipe.java:190) ~[ars_nouveau-1.18.1-2.0.2.jar%2355!:2.0.2]
	at net.minecraft.world.item.crafting.RecipeManager.m_44045_(RecipeManager.java:144) ~[client-1.18.1-20211210.034407-srg.jar%23125!:?]
	at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:60) ~[client-1.18.1-20211210.034407-srg.jar%23125!:?]
	at shadows.fastsuite.AuxRecipeManager.m_5787_(AuxRecipeManager.java:35) ~[FastSuite-1.18.1-3.0.0.jar%2375!:3.0.0]
	at shadows.fastsuite.AuxRecipeManager.m_5787_(AuxRecipeManager.java:22) ~[FastSuite-1.18.1-3.0.0.jar%2375!:3.0.0]
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13) ~[client-1.18.1-20211210.034407-srg.jar%23125!:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:71) ~[client-1.18.1-20211210.034407-srg.jar%23125!:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[client-1.18.1-20211210.034407-srg.jar%23125!:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.1-20211210.034407-srg.jar%23125!:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:125) ~[client-1.18.1-20211210.034407-srg.jar%23125!:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:134) ~[client-1.18.1-20211210.034407-srg.jar%23125!:?]
	at net.minecraft.client.Minecraft.m_91190_(Minecraft.java:2071) ~[client-1.18.1-20211210.034407-srg.jar%23125!:?]
	at net.minecraft.client.Minecraft.doLoadLevel(Minecraft.java:1903) ~[client-1.18.1-20211210.034407-srg.jar%23125!:?]
	at net.minecraft.client.Minecraft.m_91202_(Minecraft.java:2854) ~[client-1.18.1-20211210.034407-srg.jar%23125!:?]
	at net.minecraft.client.gui.screens.worldselection.CreateWorldScreen.m_100972_(CreateWorldScreen.java:240) ~[client-1.18.1-20211210.034407-srg.jar%23125!:?]
	at net.minecraft.client.gui.screens.worldselection.CreateWorldScreen.lambda$init$13(CreateWorldScreen.java:181) ~[client-1.18.1-20211210.034407-srg.jar%23125!:?]
	at net.minecraft.client.gui.components.Button.m_5691_(Button.java:40) ~[client-1.18.1-20211210.034407-srg.jar%23125!:?]
	at net.minecraft.client.gui.components.AbstractButton.m_5716_(AbstractButton.java:16) ~[client-1.18.1-20211210.034407-srg.jar%23125!:?]
	at net.minecraft.client.gui.components.AbstractWidget.m_6375_(AbstractWidget.java:111) ~[client-1.18.1-20211210.034407-srg.jar%23125!:?]
	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_6375_(ContainerEventHandler.java:27) ~[client-1.18.1-20211210.034407-srg.jar%23125!:?]
	at net.minecraft.client.MouseHandler.lambda$onPress$0(MouseHandler.java:88) ~[client-1.18.1-20211210.034407-srg.jar%23125!:?]
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:527) ~[client-1.18.1-20211210.034407-srg.jar%23125!:?]
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:85) ~[client-1.18.1-20211210.034407-srg.jar%23125!:?]
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.18.1-20211210.034407-srg.jar%23125!:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:101) ~[client-1.18.1-20211210.034407-srg.jar%23125!:?]
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.18.1-20211210.034407-srg.jar%23125!:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar%2348!:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar%2344!:build 10]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar%2348!:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:202) ~[client-1.18.1-20211210.034407-srg.jar%23125!:?]
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:333) ~[client-1.18.1-20211210.034407-srg.jar%23125!:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1062) ~[client-1.18.1-20211210.034407-srg.jar%23125!:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:660) ~[client-1.18.1-20211210.034407-srg.jar%23125!:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%23125!:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.0.10.jar%2323!:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?]
```

**Comment by JaisDK** [comment]
1.16 or 1.18?

**Comment by coldReactive** [comment]
Sorry, forgot to say it was 1.18. Also not sure if this crash is related to it:

Crash Report: https://pastebin.com/fKS4CHSh
Debug Log: https://pastebin.com/psQhPDJz
Latest Log: https://pastebin.com/zLi7it5D

Crash Happened when I spawned a bee.

**Comment by JaisDK** [comment]
did you launch the game again after the crash? the logs do not have the crash in them
from the crash report I don't see anything bee relation, but could you try spawning the same and see if it happens again? which bee did you spawn?

whatever it is, it's not related to the recipe error

**Comment by coldReactive** [comment]
I think it's Neat. /cough

No really. neat is crashing with bee spawns for some reason. I mean all bees, even Vanilla ones: https://www.curseforge.com/minecraft/mc-mods/neat

**Comment by JaisDK** [comment]
I see you reported it to them 👍
