### ISSUE TITLE
(1.18.2) Game Crash When Inserting Non-Bee into Incubator

### ISSUE THREAD

**Issue by its0keke** [JDKDigital/productive-bees#318]
Hi there, I looked through the reported issues and it seems like this hasn't been reported.

I accidentally shift-clicked a mekanism configurator into the Incubator while I had a bee in a cage in the first slot and my game crashed. My guess is that it still tried to find a recipe with the configurator and eventually timed out or something.

(This is while playing ATM7 Skyblock v1.0.9)

**Comment by its0keke** [comment]
Looks like this is the relevant error. Going to need to figure out how to undo this before I'm able to open the save again lol

```
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.animal.Bee.m_20078_()" because "bee2" is null
	at cy.jdkdigital.productivebees.util.BeeHelper$IdentifierInventory.<init>(BeeHelper.java:496) ~[productivebees-1.18.2-0.9.1.5.jar%23242!/:1.18.2-0.9.1.5] {re:classloading}
	at cy.jdkdigital.productivebees.util.BeeHelper.getBreedingRecipes(BeeHelper.java:176) ~[productivebees-1.18.2-0.9.1.5.jar%23242!/:1.18.2-0.9.1.5] {re:classloading}
	at cy.jdkdigital.productivebees.common.block.entity.BreedingChamberBlockEntity.lambda$tick$4(BreedingChamberBlockEntity.java:144) ~[productivebees-1.18.2-0.9.1.5.jar%23242!/:1.18.2-0.9.1.5] {re:classloading}
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:150) ~[forge-1.18.2-40.1.79-universal.jar%23312!/:?] {re:mixin,re:classloading}
	at cy.jdkdigital.productivebees.common.block.entity.BreedingChamberBlockEntity.tick(BreedingChamberBlockEntity.java:139) ~[productivebees-1.18.2-0.9.1.5.jar%23242!/:1.18.2-0.9.1.5]
```

**Comment by JaisDK** [comment]
It's already fixed, you just need to update https://www.curseforge.com/minecraft/mc-mods/productivebees/files/4012712

**Comment by its0keke** [comment]
https://github.com/JDKDigital/productive-bees/blob/487ec54de4c847b788192406bd37609d42e0d536/src/main/java/cy/jdkdigital/productivebees/common/block/entity/BreedingChamberBlockEntity.java#L143

ah if I would've dug a bit more I would've found this. Thanks for the quick reply
