### ISSUE TITLE
[1.19.2] Division by Zero Error

### ISSUE THREAD

**Issue by Ghost295** [JDKDigital/productive-bees#327]
I am running the ATM8 modpack on a server and the server keeps crashing due to a division by 0 error.

<details>
<summary>Crash Report</summary>
<br>
java.lang.ArithmeticException: / by zero
	at cy.jdkdigital.productivebees.common.block.entity.AdvancedBeehiveBlockEntity.beesOutsideHive(AdvancedBeehiveBlockEntity.java:322) ~[productivebees-1.19.2-0.10.2.1.jar%23292!/:1.19.2-0.10.2.1] {re:classloading}
	at cy.jdkdigital.productivebees.common.block.entity.AdvancedBeehiveBlockEntity.tick(AdvancedBeehiveBlockEntity.java:110) ~[productivebees-1.19.2-0.10.2.1.jar%23292!/:1.19.2-0.10.2.1] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:687) ~[server-1.19.2-20220805.130853-srg.jar%23369!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:780) ~[server-1.19.2-20220805.130853-srg.jar%23369!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.world.level.Level.m_46463_(Level.java:446) ~[server-1.19.2-20220805.130853-srg.jar%23369!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.WorldMixin,pl:mixin:APP:canary.mixins.json:world.block_entity_retrieval.WorldMixin,pl:mixin:APP:canary.mixins.json:world.block_entity_ticking.sleeping.WorldMixin,pl:mixin:APP:canary.mixins.json:world.chunk_access.WorldMixin,pl:mixin:APP:canary.mixins.json:world.inline_block_access.WorldMixin,pl:mixin:APP:canary.mixins.json:world.inline_height.WorldMixin,pl:mixin:APP:lootr.mixins.json:MixinLevel,pl:mixin:APP:utilitix.mixins.json:MixinLevel,pl:mixin:APP:itshallnottick.mixins.json:EntityTickMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinWorld,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:331) ~[server-1.19.2-20220805.130853-srg.jar%23369!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:canary.mixins.json:ai.nearby_entity_tracking.ServerWorldAccessor,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.ServerWorldMixin,pl:mixin:APP:canary.mixins.json:chunk.entity_class_groups.ServerWorldAccessor,pl:mixin:APP:canary.mixins.json:entity.inactive_navigations.ServerWorldMixin,pl:mixin:APP:canary.mixins.json:profiler.ServerWorldMixin,pl:mixin:APP:byg.mixins.json:common.world.MixinServerLevel,pl:mixin:APP:enhancedcelestials.mixins.json:MixinServerWorld,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[server-1.19.2-20220805.130853-srg.jar%23369!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23369!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:nochatreports.mixins.json:server.MixinDedicatedServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23369!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23369!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23369!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}
</details>

**Comment by JaisDK** [comment]
Did you change the speed upgrade configs to something else than 0.2?

**Comment by Ghost295** [comment]
Yes, to 0.4. Should I change it back to default?

**Comment by JaisDK** [comment]
yes, set it to something less than 0.25 and I'll get it fixed soon so you can have it higher.

what happens is that you get 100%+ hive time reduction making the bees stay inside the hive 0 ticks and somewhere in the code this number is used in some math which breaks.

**Comment by Ghost295** [comment]
Using the simulator upgrade does seem to help. I'll change it to less than 0.25 for now then.
Thank you

**Comment by AvremelM** [comment]
Just noting that this happens in 1.18.2 as well (ATM7-TTS)

**Comment by JaisDK** [comment]
Did you change your config too?

**Comment by AvremelM** [comment]
Yes. I changed it back manually in the .toml, so it's fine for now. 
Just noting that the issue isn't only in 1.19.2 (like the title).
