### ISSUE TITLE
Please help with JEI

### ISSUE THREAD

**Issue by neka4am** [JDKDigital/productive-bees#373]
Hi, im playing on forge 1.19.3 (44.1.23) and i when i first installed productive bees i was able to see bees in JEI but then it just disappered.  I was using JEI 12.3.0.20, and i tried to install newer and older versions but nothing changes. Please recommend the version of JEI or maybe im doing something wrong? Thank you

**Comment by JaisDK** [comment]
which version of productive bees are you having and are you playing single player or on a server?

**Comment by neka4am** [comment]
im playing on my own server, 0.11.1.0 version

**Comment by JaisDK** [comment]
can you provide some logs both server and client side?

**Comment by neka4am** [comment]
https://mclo.gs/WLMTr1H
server logs

![image](https://user-images.githubusercontent.com/131824083/234427028-1f618167-f6ed-4ddd-89b4-cc67aaf418f1.png)
im not actually in this thing so what i should send you?

**Comment by JaisDK** [comment]
latest

**Comment by neka4am** [comment]
[latest.log](https://github.com/JDKDigital/productive-bees/files/11327471/latest.log)

**Comment by JaisDK** [comment]
looks like an incompatibility with MCA

**Comment by neka4am** [comment]
strange, i got mca earlier than productive bees and i saw bees

**Comment by JaisDK** [comment]
ore more specifically, it looks like `mca:male_villager` is found in the registry but the value is null

did you remove MCA or did it update?

**Comment by neka4am** [comment]
no, but i had bug with villager what just disappered, it in the registry but he really not exist and it wasnt killed

**Comment by JaisDK** [comment]
probably what caused it

it's something I can work around on my end I just need to have time for an update

**Comment by neka4am** [comment]
should i try delete and install mca?

**Comment by JaisDK** [comment]
see if it helps, they do add some kind of "hack" in there


```

Caused by: java.lang.NullPointerException: Registry Object not present: mca:male_villager
	at dev.architectury.registry.registries.DeferredRegister$Entry.get(DeferredRegister.java:133) ~[architectury-7.1.78-forge.jar%23230!/:?]
	at net.minecraft.world.entity.EntityType.handler$zbc000$mca$villagerTagHack(EntityType.java:718) ~[client-1.19.3-20221207.122022-srg.jar%23306!/:?]
	at net.minecraft.world.entity.EntityType.m_204039_(EntityType.java) ~[client-1.19.3-20221207.122022-srg.jar%23306!/:?]
	at cy.jdkdigital.productivebees.integrations.jei.ingredients.BeeIngredientFactory.getOrCreateList(BeeIngredientFactory.java:55) ~[productivebees-1.19.3-0.11.1.0.jar%23277!/:1.19.3-0.11.1.0]
	at cy.jdkdigital.productivebees.integrations.jei.ProductiveBeesJeiPlugin.<init>(ProductiveBeesJeiPlugin.java:70) ~[productivebees-1.19.3-0.11.1.0.jar%23277!/:1.19.3-0.11.1.0]

```

**Comment by neka4am** [comment]
thank you!!

**Comment by JaisDK** [comment]
looks like they have a config to turn off that hack, look for villagerTagsHacks in their config file
