### ISSUE TITLE
trying to make bee

### ISSUE THREAD

**Issue by MxDeath** [JDKDigital/productive-bees#505]
So i'm no expert at doing any of this. I did update my graphics. Trying to add my own bee has been a real trial and error process. I feel like i'm really close to having it but I've hit a spot where I keep crashing.  I get Error exitcode -1

[crash-2024-06-15_17.30.46-client.txt](https://github.com/user-attachments/files/15855300/crash-2024-06-15_17.30.46-client.txt)

This is the crash report I receive, I honestly don't know what's wrong. Any help would be much appreciated

**Comment by JaisDK** [comment]
Can you share the code you made for the bee?

**Comment by MxDeath** [comment]
[pinky.json](https://github.com/user-attachments/files/15855307/pinky.json)
[pinky_bee.json](https://github.com/user-attachments/files/15855308/pinky_bee.json)
[pinky_bee.json](https://github.com/user-attachments/files/15855309/pinky_bee.json)
[honeycomb_pinky.json](https://github.com/user-attachments/files/15855310/honeycomb_pinky.json)

i hope these work, please let me know if they dont

**Comment by JaisDK** [comment]
if you add `"beeTexture": "productivebees:textures/entity/bee/slimy/bee",` to the bee configuration, does it stop crashing?
if it stops then you must have a custom texture to use the `translucent_with_center` renderer

**Comment by MxDeath** [comment]
okay so that was the inital issues, but i did have my own textures on standby. unfortunely when i tried to add them, the bee was invisible in game. checking the log report this is what was given


[17:59:24] [Render thread/INFO]: Registering commands with com.sk89q.worldedit.forge.ForgePlatform
[17:59:25] [Worker-Main-11/ERROR]: Couldn't parse data file productivebees:pinky from productivebees:productivebees/pinky.json
com.google.gson.JsonParseException: com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 5 column 22 path $.beeTexture
	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:526) ~[client-1.20.1-20230612.114412-srg.jar%23214!/:?]
	at net.minecraft.util.GsonHelper.m_263475_(GsonHelper.java:531) ~[client-1.20.1-20230612.114412-srg.jar%23214!/:?]
	at net.minecraft.util.GsonHelper.m_13776_(GsonHelper.java:581) ~[client-1.20.1-20230612.114412-srg.jar%23214!/:?]
	at net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener.m_278771_(SimpleJsonResourceReloadListener.java:41) ~[client-1.20.1-20230612.114412-srg.jar%23214!/:?]
	at net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener.m_5944_(SimpleJsonResourceReloadListener.java:29) ~[client-1.20.1-20230612.114412-srg.jar%23214!/:?]
	at cy.jdkdigital.productivebees.setup.BeeReloadListener.m_5944_(BeeReloadListener.java:39) ~[productivebees-1.20.1-12.5.3.jar%23205!/:1.20.1-12.5.3]
	at cy.jdkdigital.productivebees.setup.BeeReloadListener.m_5944_(BeeReloadListener.java:23) ~[productivebees-1.20.1-12.5.3.jar%23205!/:1.20.1-12.5.3]
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10786_(SimplePreparableReloadListener.java:11) ~[client-1.20.1-20230612.114412-srg.jar%23214!/:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 5 column 22 path $.beeTexture
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1657) ~[gson-2.10.jar%23107!/:?]
	at com.google.gson.stream.JsonReader.readEscapeCharacter(JsonReader.java:1648) ~[gson-2.10.jar%23107!/:?]
	at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1025) ~[gson-2.10.jar%23107!/:?]
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:824) ~[gson-2.10.jar%23107!/:?]
	at com.google.gson.internal.bind.TypeAdapters$28.readTerminal(TypeAdapters.java:747) ~[gson-2.10.jar%23107!/:?]
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:791) ~[gson-2.10.jar%23107!/:?]
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:725) ~[gson-2.10.jar%23107!/:?]
	at com.google.gson.internal.bind.TypeAdapters$34$1.read(TypeAdapters.java:1007) ~[gson-2.10.jar%23107!/:?]
	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:524) ~[client-1.20.1-20230612.114412-srg.jar%23214!/:?]
	... 14 more

**Comment by MxDeath** [comment]
[pinky.json](https://github.com/user-attachments/files/15855402/pinky.json)


this is what i did to add the textures

**Comment by JaisDK** [comment]
there's no beeTexture entry in that file

**Comment by MxDeath** [comment]
my bad! this is what i got
{
  "primaryColor": "#ffb3c9",
  "secondaryColor": "#b82b54",
  "particleColor": "#ffdcc4",
  "beeTexture": "C:\Users\shann\Documents\Instances\bap\saves\New World\datapacks\pb\data\productivebees\textures\entity\bee\pinky",
  "flowerTag": "productivebees:flowers/swamp_flowers",
  "slimy": true,
  "renderer": "translucent_with_center",
  "attributes": {
    "temper": 0
  }
}

**Comment by JaisDK** [comment]
you can't put a path to your computer, you have to put the textures in a resourcepack and use a path to that

"productivebees:textures/entity/bee/pinky/bee"

**Comment by MxDeath** [comment]
Apologies, i'm very new at this. Would making a resource pack be in the texture pack itself? or in the general resource packs? I tried to add them in and i thought I had it right. i'm getting closer but the bees now load in as error cubes? Thank you so much for helping and your patience

**Comment by JaisDK** [comment]
resource packs are textures packs, just the new name for them
the bee file and it's recipes go into the data pack, the textures into a resource pack

**Comment by MxDeath** [comment]
i have the textures in the pack, this is what i got from it. I'm really sorry 

[18:33:26] [Render thread/WARN]: Failed to load texture: productivebees:textures/entity/bee/pinky/bee.png
java.io.FileNotFoundException: productivebees:textures/entity/bee/pinky/bee.png
	at net.minecraft.server.packs.resources.ResourceProvider.m_215590_(ResourceProvider.java:21) ~[client-1.20.1-20230612.114412-srg.jar%23214!/:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.server.packs.resources.ResourceProvider.m_215593_(ResourceProvider.java:21) ~[client-1.20.1-20230612.114412-srg.jar%23214!/:?]
	at net.minecraft.client.renderer.texture.SimpleTexture$TextureImage.m_118155_(SimpleTexture.java:83) ~[client-1.20.1-20230612.114412-srg.jar%23214!/:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.m_6335_(SimpleTexture.java:58) ~[client-1.20.1-20230612.114412-srg.jar%23214!/:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.m_6704_(SimpleTexture.java:29) ~[client-1.20.1-20230612.114412-srg.jar%23214!/:?]
	at net.minecraft.client.renderer.texture.TextureManager.m_118515_(TextureManager.java:96) ~[client-1.20.1-20230612.114412-srg.jar%23214!/:?]
	at net.minecraft.client.renderer.texture.TextureManager.m_118495_(TextureManager.java:66) ~[client-1.20.1-20230612.114412-srg.jar%23214!/:?]
	at net.minecraft.client.renderer.texture.TextureManager.m_118506_(TextureManager.java:119) ~[client-1.20.1-20230612.114412-srg.jar%23214!/:?]
	at net.minecraft.client.renderer.RenderStateShard$TextureStateShard.m_263890_(RenderStateShard.java:243) ~[client-1.20.1-20230612.114412-srg.jar%23214!/:?]
	at net.minecraft.client.renderer.RenderStateShard.m_110185_(RenderStateShard.java:37) ~[client-1.20.1-20230612.114412-srg.jar%23214!/:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.1-jre.jar%23109!/:?]
	at net.minecraft.client.renderer.RenderType$CompositeRenderType.m_110526_(RenderType.java:490) ~[client-1.20.1-20230612.114412-srg.jar%23214!/:?]
	at net.minecraft.client.renderer.RenderStateShard.m_110185_(RenderStateShard.java:37) ~[client-1.20.1-20230612.114412-srg.jar%23214!/:?]
	at net.minecraft.client.renderer.RenderType.m_276775_(RenderType.java:433) ~[client-1.20.1-20230612.114412-srg.jar%23214!/:?]
	at net.minecraft.client.renderer.MultiBufferSource$BufferSource.m_109912_(MultiBufferSource.java:97) ~[client-1.20.1-20230612.114412-srg.jar%23214!/:?]
	at net.minecraft.client.renderer.MultiBufferSource$BufferSource.m_173043_(MultiBufferSource.java:65) ~[client-1.20.1-20230612.114412-srg.jar%23214!/:?]
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1228) ~[client-1.20.1-20230612.114412-srg.jar%23214!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1126) ~[client-1.20.1-20230612.114412-srg.jar%23214!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:909) ~[client-1.20.1-20230612.114412-srg.jar%23214!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23214!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23214!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.2.0.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.0.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.0.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]

**Comment by JaisDK** [comment]
now you just need to move the files from `bap\saves\New World\datapacks\pb\data\productivebees\textures\entity\bee\pinky` into `bap\resourcepacks\pb\assets\productivebees\textures\entity\bee\pinky`

**Comment by MxDeath** [comment]
![bee](https://github.com/JDKDigital/productive-bees/assets/85132045/98de1e42-6e8e-4c30-b823-2b18b6a4d316)
![bee_angry](https://github.com/JDKDigital/productive-bees/assets/85132045/81aabaee-d3f1-4cb1-9bc1-c86d585849a8)
![bee_angry_nectar](https://github.com/JDKDigital/productive-bees/assets/85132045/6382a483-c449-4111-b13d-75c9f9c014c1)
![bee_nectar](https://github.com/JDKDigital/productive-bees/assets/85132045/6f46f45f-8318-400e-9bc4-e63058d429d4)
[pinky.json](https://github.com/user-attachments/files/15855559/pinky.json)

[latest.log](https://github.com/user-attachments/files/15855562/latest.log)


i forgot the pb and asset folder at first. I did add that, I reloaded everything, minecraft, the folders. I double checked that there was no capitals or spaces or anything misspelled. All my textures are pngs yet any time i try to load it in, i get error cubes? I genuinely dont know where im going wrong

**Comment by JaisDK** [comment]
is the resource pack enabled?

**Comment by MxDeath** [comment]
would it be with the mod resource packs? if so then yes. If the resource pack is suppose to pop up on its own then im uncertain
![Screenshot (178)](https://github.com/JDKDigital/productive-bees/assets/85132045/2cf2a288-1c7f-49aa-9ea5-eaa449e74f86)

**Comment by JaisDK** [comment]
it's supposed to be its own when you put it in the resourcepacks folder

**Comment by MxDeath** [comment]
then its not showing up for me in game? but i have it in the resourcepacks folder

**Comment by JaisDK** [comment]
did you add an .mcmeta file to it? it's required for a resource or data pack

**Comment by MxDeath** [comment]
that was it! I got it working now! Thank you so so much for your help, you're amazing!

**Comment by MxDeath** [comment]
![Screenshot (183)](https://github.com/JDKDigital/productive-bees/assets/85132045/e32b23f7-9aae-4eab-8b17-aa69ecc49113)

Hey i'm having one last issue, the name of my bee doesn't seem to be loading in correctly? I've double checked everything, and added    "name": "Pinkie",   to the .json file yet it keeps loading in like this

**Comment by MxDeath** [comment]
closing
