### ISSUE TITLE
Is it possible to fix the error with EMI?

### ISSUE THREAD

**Issue by Lolothepro** [JDKDigital/productive-bees#517]
```
Thread-30/ERROR] [EMI/]: [EMI] Exception loading plugin provided by productivebees
net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: productivebees:/quarry_bee/minecraft:dirt
[15:56:02] [Thread-30/ERROR] [EMI/]: [EMI] net.minecraft.ResourceLocationException: Non [a-z0-9
	at TRANSFORMER/minecraft@1.21/net.minecraft.resources.ResourceLocation.assertValidPath(ResourceLocation.java:284)
	at TRANSFORMER/minecraft@1.21/net.minecraft.resources.ResourceLocation.createUntrusted(ResourceLocation.java:48)
	at TRANSFORMER/minecraft@1.21/net.minecraft.resources.ResourceLocation.fromNamespaceAndPath(ResourceLocation.java:52)
	at TRANSFORMER/productivebees@1.21.0-13.1.1/cy.jdkdigital.productivebees.compat.emi.ProductiveBeesEmiPlugin.lambda$addBlockDupeRecipes$18(ProductiveBeesEmiPlugin.java:197)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at TRANSFORMER/productivebees@1.21.0-13.1.1/cy.jdkdigital.productivebees.compat.emi.ProductiveBeesEmiPlugin.addBlockDupeRecipes(ProductiveBeesEmiPlugin.java:192)
	at TRANSFORMER/productivebees@1.21.0-13.1.1/cy.jdkdigital.productivebees.compat.emi.ProductiveBeesEmiPlugin.register(ProductiveBeesEmiPlugin.java:183)
	at TRANSFORMER/emi@1.1.10+1.21+neoforge/dev.emi.emi.runtime.EmiReloadManager$ReloadWorker.run(EmiReloadManager.java:185)
	at java.base/java.lang.Thread.run(Thread.java:1583)
[15:56:02] [Thread-30/ERROR] [EMI/]: [EMI] ._-] character in path of location: productivebees:
[15:56:02] [Thread-30/ERROR] [EMI/]: [EMI] quarry_bee
[15:56:02] [Thread-30/ERROR] [EMI/]: [EMI] minecraft:dirt
	at TRANSFORMER
[15:56:02] [Thread-30/ERROR] [EMI/]: [EMI] minecraft@1.21
[15:56:02] [Thread-30/ERROR] [EMI/]: [EMI] net.minecraft.resources.ResourceLocation.assertValidPath(ResourceLocation.java:284)
	at TRANSFORMER
[15:56:02] [Thread-30/ERROR] [EMI/]: [EMI] minecraft@1.21
[15:56:02] [Thread-30/ERROR] [EMI/]: [EMI] net.minecraft.resources.ResourceLocation.createUntrusted(ResourceLocation.java:48)
	at TRANSFORMER
[15:56:02] [Thread-30/ERROR] [EMI/]: [EMI] minecraft@1.21
[15:56:02] [Thread-30/ERROR] [EMI/]: [EMI] net.minecraft.resources.ResourceLocation.fromNamespaceAndPath(ResourceLocation.java:52)
	at TRANSFORMER
[15:56:02] [Thread-30/ERROR] [EMI/]: [EMI] productivebees@1.21.0-13.1.1
[15:56:02] [Thread-30/ERROR] [EMI/]: [EMI] cy.jdkdigital.productivebees.compat.emi.ProductiveBeesEmiPlugin.lambda$addBlockDupeRecipes$18(ProductiveBeesEmiPlugin.java:197)
	at java.base
[15:56:02] [Thread-30/ERROR] [EMI/]: [EMI] java.lang.Iterable.forEach(Iterable.java:75)
	at TRANSFORMER
[15:56:02] [Thread-30/ERROR] [EMI/]: [EMI] productivebees@1.21.0-13.1.1
[15:56:02] [Thread-30/ERROR] [EMI/]: [EMI] cy.jdkdigital.productivebees.compat.emi.ProductiveBeesEmiPlugin.addBlockDupeRecipes(ProductiveBeesEmiPlugin.java:192)
	at TRANSFORMER
[15:56:02] [Thread-30/ERROR] [EMI/]: [EMI] productivebees@1.21.0-13.1.1
[15:56:02] [Thread-30/ERROR] [EMI/]: [EMI] cy.jdkdigital.productivebees.compat.emi.ProductiveBeesEmiPlugin.register(ProductiveBeesEmiPlugin.java:183)
	at TRANSFORMER
[15:56:02] [Thread-30/ERROR] [EMI/]: [EMI] emi@1.1.10+1.21+neoforge
[15:56:02] [Thread-30/ERROR] [EMI/]: [EMI] dev.emi.emi.runtime.EmiReloadManager$ReloadWorker.run(EmiReloadManager.java:185)
	at java.base
[15:56:02] [Thread-30/ERROR] [EMI/]: [EMI] java.lang.Thread.run(Thread.java:1583)

```
This error

**Comment by JaisDK** [comment]
Yes it’s very easy to fix. Update the mod.
