### ISSUE TITLE
Opening gui causes to crash the game

### ISSUE THREAD

**Issue by Seanniex** [JDKDigital/productive-bees#72]
I'm currently playing on 1.16.2 with jei 

When I open the advanced beehive and close them for a second the game crash. This also applies in the centrifuge and when viewing recipes with jei 

Here's the lastest crash report

Description: Ticking block entity

java.lang.NoSuchMethodError: net.minecraftforge.common.util.LazyOptional.map(Lnet/minecraftforge/common/util/NonNullFunction;)Lnet/minecraftforge/common/util/LazyOptional;
	at cy.jdkdigital.productivebees.tileentity.AdvancedBeehiveTileEntityAbstract.getBeeListAsNBTList(AdvancedBeehiveTileEntityAbstract.java:302) ~[?:1.16.2-0.2.5] {re:classloading}
	at cy.jdkdigital.productivebees.tileentity.AdvancedBeehiveTileEntity.func_73660_a(AdvancedBeehiveTileEntity.java:92) ~[?:1.16.2-0.2.5] {re:classloading}
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:366) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:repurposed_structures.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:782) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:repurposed_structures.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:120) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:637) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:repurposed_structures.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:repurposed_structures.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$6164/1728410642.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at cy.jdkdigital.productivebees.tileentity.AdvancedBeehiveTileEntityAbstract.getBeeListAsNBTList(AdvancedBeehiveTileEntityAbstract.java:302)
	at cy.jdkdigital.productivebees.tileentity.AdvancedBeehiveTileEntity.func_73660_a(AdvancedBeehiveTileEntity.java:92)

-- Block entity being ticked --
Details:
	Name: productivebees:advanced_beehive // cy.jdkdigital.productivebees.tileentity.AdvancedBeehiveTileEntity
	Block: Block{productivebees:advanced_oak_beehive}[expanded=none,facing=north,honey_level=0]
	Block location: World: (65,64,177), Chunk: (at 1,4,1 in 4,11; contains blocks 64,0,176 to 79,255,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Block: Block{productivebees:advanced_oak_beehive}[expanded=none,facing=north,honey_level=0]
	Block location: World: (65,64,177), Chunk: (at 1,4,1 in 4,11; contains blocks 64,0,176 to 79,255,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Stacktrace:
	at net.minecraft.world.World.func_217391_K(World.java:491)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:366)

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['SeanzXZ'/250, l='ServerLevel[New World nieuwnrowe]', x=66.15, y=66.92, z=173.39]]
	Chunk stats: ServerChunkCache: 2226
	Level dimension: minecraft:overworld
	Level spawn location: World: (160,82,112), Chunk: (at 0,5,0 in 10,7; contains blocks 160,0,112 to 175,255,127), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 105770 game time, 37316 day time
	Level name: New World nieuwnrowe
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 142130 (now: false), thunder time: 89686 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:782)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:120)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:637)
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229)
	at net.minecraft.server.MinecraftServer$$Lambda$6164/1728410642.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.16.2
	Minecraft Version ID: 1.16.2
	Operating System: Windows 8 (amd64) version 6.2
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2680905584 bytes (2556 MB) / 4060086272 bytes (3872 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 6.1.1+74+master.966c698
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.2-33.0.22.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.2-33.0.22.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.2-33.0.22.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.2-33.0.22.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.jar mixin TRANSFORMATIONSERVICE 
		/preview_OptiFine_1.16.2_HD_U_G3_pre6.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.2-33.0.22.jar fml TRANSFORMATIONSERVICE 
	FML: 33.0
	Forge: net.minecraftforge:33.0.22
	FML Language Providers: 
		javafml@33.0
		minecraft@1
	Mod List: 
		forge-1.16.2-33.0.22-client.jar Minecraft {minecraft@1.16.2 DONE}
		repurposed_structures-1.16.2-2.1.0.jar Repurposed Structures {repurposed_structures@1.16.2-2.1.0 DONE}
		netherportalspread_1.16.2-3.5.jar Nether Portal Spread {netherportalspread@3.5 DONE}
		mining-helmet-1.16.2-1.0.8.jar Mining Helmet {mining_helmet@1.0.8 DONE}
		jei-1.16.2-7.1.1.15.jar Just Enough Items {jei@7.1.1.15 DONE}
		RallyHealth-1.16.2-1.1.jar Rally Health {rallyhealth@1.1 DONE}
		strawgolem-1.16.2-1.9-beta-2.jar Straw Golem {strawgolem@1.16-1.9-beta-2 DONE}
		BetterCaves-1.16.2-1.0.jar YUNG's Better Caves {bettercaves@1.16.2-1.0 DONE}
		leap-1.16.2-1.0.1.jar Leap {leap@1.0.1 DONE}
		collective-1.16.2-1.38.jar Collective {collective@1.38 DONE}
		buildersaddition-20200824d.jar Builders Crafts & Addition {buildersaddition@20200824d DONE}
		simpleplanes-1.16.2-2.0.5.3.jar Simple Planes {simpleplanes@1.16.2-2.0.5.3 DONE}
		cryingghasts_1.16.2-1.1.jar Crying Ghasts {cryingghasts@1.1 DONE}
		AI-Improvements-1.16.2-0.3.0.jar AI-Improvements {aiimprovements@0.3.0 DONE}
		fakename-1.16.2-1.4.0.9.jar Fakename {fakename@1.4.0.9 DONE}
		productivebees-1.16.2-0.2.5.jar Productive Bees {productivebees@1.16.2-0.2.5 DONE}
		fixedanvilrepaircost_1.16.2-1.1.jar Fixed Anvil Repair Cost {fixedanvilrepaircost@1.1 DONE}
		dismountentity_1.16.2-1.2.jar Dismount Entity {dismountentity@1.2 DONE}
		forge-1.16.2-33.0.22-universal.jar Forge {forge@33.0.22 DONE}
		scuba-gear-1.16.2-1.0.1.jar Scuba Gear {scuba_gear@1.0.1 DONE}
		RevampedWolf-1.16.2-0.6.0.jar RevampedWolf {revampedwolf@1.16.2-0.6.0 DONE}
		CosmeticArmorReworked-1.16.2-v1.jar CosmeticArmorReworked {cosmeticarmorreworked@1.16.2-v1 DONE}
		travellers_map-1.16.2-0.6.1.jar Travellers Map {travellers_map@1.16.2-0.6 DONE}
		entityarmormodels-1.16.2-1.0.0.0.jar �1Entity �cArmor �fModels {entityarmormodels@1.16.2-1.0.0.0 DONE}
		conduitsprdrowned_1.16.2-1.1.jar Conduits Prevent Drowned {conduitsprdrowned@1.1 DONE}
		dash-1.16.2-1.0.1.jar Dash {dash@1.0.1 DONE}
	Player Count: 1 / 8; [ServerPlayerEntity['SeanzXZ'/250, l='ServerLevel[New World nieuwnrowe]', x=66.15, y=66.92, z=173.39]]
	Data Packs: vanilla, mod:repurposed_structures (incompatible), mod:netherportalspread, mod:mining_helmet (incompatible), mod:jei, mod:rallyhealth, mod:strawgolem, mod:bettercaves (incompatible), mod:leap (incompatible), mod:collective, mod:buildersaddition (incompatible), mod:simpleplanes (incompatible), mod:cryingghasts, mod:aiimprovements, mod:fakename (incompatible), mod:productivebees (incompatible), mod:fixedanvilrepaircost, mod:dismountentity, mod:forge (incompatible), mod:scuba_gear (incompatible), mod:revampedwolf, mod:cosmeticarmorreworked (incompatible), mod:travellers_map (incompatible), mod:entityarmormodels (incompatible), mod:conduitsprdrowned, mod:dash (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
	OptiFine Version: OptiFine_1.16.2_HD_U_G3_pre6
	OptiFine Build: 20200827-182750
	Render Distance Chunks: 9
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 - Build 23.20.16.5038
	OpenGlRenderer: Intel(R) UHD Graphics 620
	OpenGlVendor: Intel
	CpuCount: 8

**Comment by JaisDK** [comment]
There was no JEI when I did the 1.16.2 version, so I probably jut need to update some code. I'll get a fixed version out soon.

**Comment by JaisDK** [comment]
I am not getting a crash, but can you check if this version works for you? It's compiled with the latest Forge version and tested with the version of JEI you have installed. (You'll need to unzip it)

[productivebees-1.16.2-0.2.6.zip](https://github.com/JDKDigital/productive-bees/files/5147023/productivebees-1.16.2-0.2.6.zip)

**Comment by Seanniex** [comment]
thank you! it no longer crashes the game but I also discover a bug, when you shift-click a bottled honey in the bottler the game crashes.

Here is the crash report
Description: Container click

java.lang.ArrayIndexOutOfBoundsException: -7
	at java.util.ArrayList.elementData(ArrayList.java:418) ~[?:1.8.0_51] {}
	at java.util.ArrayList.get(ArrayList.java:431) ~[?:1.8.0_51] {}
	at net.minecraft.inventory.container.Container.func_75135_a(Container.java:501) ~[?:?] {re:classloading}
	at cy.jdkdigital.productivebees.container.AbstractContainer.func_82846_b(AbstractContainer.java:55) ~[?:1.16.2-0.2.6] {re:classloading}
	at cy.jdkdigital.productivebees.container.BottlerContainer.func_82846_b(BottlerContainer.java:24) ~[?:1.16.2-0.2.6] {re:classloading}
	at net.minecraft.inventory.container.Container.func_241440_b_(Container.java:255) ~[?:?] {re:classloading}
	at net.minecraft.inventory.container.Container.func_184996_a(Container.java:160) ~[?:?] {re:classloading}
	at net.minecraft.client.multiplayer.PlayerController.func_187098_a(PlayerController.java:379) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_184098_a(ContainerScreen.java:539) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_231044_a_(ContainerScreen.java:336) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:87) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$5200/367273163.run(Unknown Source) ~[?:?] {}
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:425) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:175) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$5199/1296316997.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(ThreadTaskExecutor.java:104) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default,re:mixin,pl:accesstransformer:B}
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:174) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$4287/570038756.invoke(Unknown Source) ~[?:?] {}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:102) ~[?:?] {re:classloading}
	at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:384) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:974) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:585) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.2-33.0.22.jar:33.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$432/1104654975.call(Unknown Source) [forge-1.16.2-33.0.22.jar:33.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-6.1.1.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at net.minecraft.inventory.container.Container.func_75135_a(Container.java:501)
	at cy.jdkdigital.productivebees.container.AbstractContainer.func_82846_b(AbstractContainer.java:55)
	at cy.jdkdigital.productivebees.container.BottlerContainer.func_82846_b(BottlerContainer.java:24)
	at net.minecraft.inventory.container.Container.func_241440_b_(Container.java:255)

-- Click info --
Details:
	Menu Type: productivebees:bottler
	Menu Class: cy.jdkdigital.productivebees.container.BottlerContainer
	Slot Count: 38
	Slot: 18
	Button: 0
	Type: QUICK_MOVE
Stacktrace:
	at net.minecraft.inventory.container.Container.func_184996_a(Container.java:160)
	at net.minecraft.client.multiplayer.PlayerController.func_187098_a(PlayerController.java:379)
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_184098_a(ContainerScreen.java:539)
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_231044_a_(ContainerScreen.java:336)
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:87)
	at net.minecraft.client.MouseHelper$$Lambda$5200/367273163.run(Unknown Source)

-- Affected screen --
Details:
	Screen name: cy.jdkdigital.productivebees.container.gui.BottlerScreen
Stacktrace:
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:425)
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85)
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:175)
	at net.minecraft.client.MouseHelper$$Lambda$5199/1296316997.run(Unknown Source)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(ThreadTaskExecutor.java:104)
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:174)
	at net.minecraft.client.MouseHelper$$Lambda$4287/570038756.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:102)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['SeanzXZ'/268, l='ClientLevel', x=-147.76, y=69.00, z=-25.98]]
	Chunk stats: Client Chunk Cache: 529, 361
	Level dimension: minecraft:overworld
	Level spawn location: World: (-144,67,-16), Chunk: (at 0,4,0 in -9,-1; contains blocks -144,0,-16 to -129,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 11878 game time, 11878 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1975)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:601)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$432/1104654975.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

**Comment by JaisDK** [comment]
I think I got both things fixed in the new version 0.3.0 just uploaded to Curseforge.
