### ISSUE TITLE
Having hives on 1.16.2 will crash the game.

### ISSUE THREAD

**Issue by modz2121** [JDKDigital/productive-bees#80]
---- Minecraft Crash Report ----
// You're mean.

Time: 9/5/20 2:43 AM
Description: Ticking entity

java.lang.NoSuchMethodError: net.minecraftforge.common.util.LazyOptional.map(Lnet/minecraftforge/common/util/NonNullFunction;)Lnet/minecraftforge/common/util/LazyOptional;
	at cy.jdkdigital.productivebees.tileentity.AdvancedBeehiveTileEntityAbstract.getBeeList(AdvancedBeehiveTileEntityAbstract.java:326) ~[?:1.16.2-0.2.5] {re:classloading}
	at cy.jdkdigital.productivebees.tileentity.AdvancedBeehiveTileEntityAbstract.func_226971_j_(AdvancedBeehiveTileEntityAbstract.java:150) ~[?:1.16.2-0.2.5] {re:classloading}
	at cy.jdkdigital.productivebees.tileentity.AdvancedBeehiveTileEntityAbstract.func_226970_h_(AdvancedBeehiveTileEntityAbstract.java:155) ~[?:1.16.2-0.2.5] {re:classloading}
	at net.minecraft.entity.passive.BeeEntity.func_226435_i_(BeeEntity.java:367) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.passive.BeeEntity.access$4700(BeeEntity.java:88) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.passive.BeeEntity$UpdateBeehiveGoal.lambda$getNearbyFreeHives$1(BeeEntity.java:1121) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.passive.BeeEntity$UpdateBeehiveGoal$$Lambda$7349/1910641479.test(Unknown Source) ~[?:?] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_51] {}
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1540) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_51] {}
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1683) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_51] {}
	at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250) ~[?:1.8.0_51] {}
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110) ~[?:1.8.0_51] {}
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270) ~[?:1.8.0_51] {}
	at net.minecraft.util.math.ChunkPos$1.tryAdvance(ChunkPos.java:216) ~[?:?] {re:classloading,xf:OptiFine:default}
	at java.util.Spliterator.forEachRemaining(Spliterator.java:326) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {}
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_51] {}
	at net.minecraft.entity.passive.BeeEntity$UpdateBeehiveGoal.func_226489_j_(BeeEntity.java:1124) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.passive.BeeEntity$UpdateBeehiveGoal.func_75249_e(BeeEntity.java:1100) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75249_e(SourceFile:41) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(GoalSelector.java:119) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:976) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2411) ~[?:?] {re:classloading}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:682) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:127) ~[?:?] {re:classloading}
	at net.minecraft.entity.passive.AnimalEntity.func_70636_d(AnimalEntity.java:51) ~[?:?] {re:classloading}
	at net.minecraft.entity.passive.BeeEntity.func_70636_d(BeeEntity.java:400) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?] {re:classloading}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:430) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.entity.passive.BeeEntity.func_70071_h_(BeeEntity.java:217) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:606) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerWorld$$Lambda$6575/218114954.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:399) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:782) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:120) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:637) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$6065/983175841.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at cy.jdkdigital.productivebees.tileentity.AdvancedBeehiveTileEntityAbstract.getBeeList(AdvancedBeehiveTileEntityAbstract.java:326)
	at cy.jdkdigital.productivebees.tileentity.AdvancedBeehiveTileEntityAbstract.func_226971_j_(AdvancedBeehiveTileEntityAbstract.java:150)
	at cy.jdkdigital.productivebees.tileentity.AdvancedBeehiveTileEntityAbstract.func_226970_h_(AdvancedBeehiveTileEntityAbstract.java:155)
	at net.minecraft.entity.passive.BeeEntity.func_226435_i_(BeeEntity.java:367)
	at net.minecraft.entity.passive.BeeEntity.access$4700(BeeEntity.java:88)
	at net.minecraft.entity.passive.BeeEntity$UpdateBeehiveGoal.lambda$getNearbyFreeHives$1(BeeEntity.java:1121)
	at net.minecraft.entity.passive.BeeEntity$UpdateBeehiveGoal$$Lambda$7349/1910641479.test(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1540)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1683)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at net.minecraft.util.math.ChunkPos$1.tryAdvance(ChunkPos.java:216)
	at java.util.Spliterator.forEachRemaining(Spliterator.java:326)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at net.minecraft.entity.passive.BeeEntity$UpdateBeehiveGoal.func_226489_j_(BeeEntity.java:1124)
	at net.minecraft.entity.passive.BeeEntity$UpdateBeehiveGoal.func_75249_e(BeeEntity.java:1100)
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75249_e(SourceFile:41)
	at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(GoalSelector.java:119)
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:976)
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2411)
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:682)
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:127)
	at net.minecraft.entity.passive.AnimalEntity.func_70636_d(AnimalEntity.java:51)
	at net.minecraft.entity.passive.BeeEntity.func_70636_d(BeeEntity.java:400)
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158)
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:430)
	at net.minecraft.entity.passive.BeeEntity.func_70071_h_(BeeEntity.java:217)
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:606)
	at net.minecraft.world.server.ServerWorld$$Lambda$6575/218114954.accept(Unknown Source)

-- Entity being ticked --
Details:
	Entity Type: minecraft:bee (net.minecraft.entity.passive.BeeEntity)
	Entity ID: 192128
	Entity Name: Bee
	Entity's Exact location: 850.60, 75.53, 572.43
	Entity's Block location: World: (850,75,572), Chunk: (at 2,4,12 in 53,35; contains blocks 848,0,560 to 863,255,575), Region: (1,1; contains chunks 32,32 to 63,63, blocks 512,0,512 to 1023,255,1023)
	Entity's Momentum: 0.02, 0.01, 0.02
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:399)

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['annaclete'/190620, l='ServerLevel[last of worlds]', x=860.48, y=75.00, z=573.46]]
	Chunk stats: ServerChunkCache: 2752
	Level dimension: minecraft:overworld
	Level spawn location: World: (352,83,272), Chunk: (at 0,5,0 in 22,17; contains blocks 352,0,272 to 367,255,287), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2266983 game time, 2556820 day time
	Level name: last of worlds
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:782)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:120)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:637)
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229)
	at net.minecraft.server.MinecraftServer$$Lambda$6065/983175841.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.16.2
	Minecraft Version ID: 1.16.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2691015376 bytes (2566 MB) / 5234491392 bytes (4992 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 6.1.1+74+master.966c698
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.2-33.0.37.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.2-33.0.37.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.2-33.0.37.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.2-33.0.37.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.jar mixin TRANSFORMATIONSERVICE 
		/preview_OptiFine_1.16.2_HD_U_G3_pre7%20(1).jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.2-33.0.37.jar fml TRANSFORMATIONSERVICE 
	FML: 33.0
	Forge: net.minecraftforge:33.0.37
	FML Language Providers: 
		javafml@33.0
		minecraft@1
	Mod List: 
		forge-1.16.2-33.0.37-client.jar Minecraft {minecraft@1.16.2 DONE}
		theoneprobe-1.16-3.0.2-beta.jar The One Probe {theoneprobe@1.16-3.0.2-beta DONE}
		nccreepers_1.16.2-1.2.jar Naturally Charged Creepers {nccreepers@1.2 DONE}
		productivebees-1.16.2-0.2.5.jar Productive Bees {productivebees@1.16.2-0.2.5 DONE}
		jei-1.16.2-7.1.3.20.jar Just Enough Items {jei@7.1.3.20 DONE}
		prefab-1.6.1.0.jar Prefab {prefab@1.6.1.0 DONE}
		HealthOverlay-1.16.2-2.1.4.jar Health Overlay {healthoverlay@NONE DONE}
		forgemod_VoxelMap-1.10.10_for_1.16.2.jar VoxelMap {voxelmap@1.10.10 DONE}
		villagespawnpoint_1.16.2-1.3.jar Village Spawn Point {villagespawnpoint@1.3 DONE}
		forge-1.16.2-33.0.37-universal.jar Forge {forge@33.0.37 DONE}
		extragolems-11.1.2.jar Extra Golems {golems@11.1.2 DONE}
		ForgeEndertech-1.16.2-7.0.2.0-build.0012.jar Forge Endertech {forgeendertech@7.0.2.0 DONE}
		AdFinders-1.16.2-5.0.2.0-build.0012.jar Advanced Finders {adfinders@5.0.2.0 DONE}
		collective-1.16.2-1.39.jar Collective {collective@1.39 DONE}
		quickhomes-1.16.2-1.2.6.jar QuickHomes {quickhomes@1.2.6 DONE}
		ore_reeds-1.16.2-1.1.4.jar Ore Reeds {ore_reeds@1.16.2-1.1.4 DONE}
		corpse-1.16.2-1.0.2.jar Corpse {corpse@1.16.2-1.0.2 DONE}
		TravelersBackpack-1.16.2-5.1.0.jar Traveler's Backpack {travelersbackpack@5.1.0 DONE}
		elementalmastery-1.16.2-0.1.3.jar Elemental Mastery {elementalmastery@1.16.2-0.1.3 DONE}
		alllootdrops_1.16.2-2.0.jar All Loot Drops {alllootdrops@2.0 DONE}
	Player Count: 1 / 8; [ServerPlayerEntity['annaclete'/190620, l='ServerLevel[last of worlds]', x=860.48, y=75.00, z=573.46]]
	Data Packs: vanilla, mod:theoneprobe (incompatible), mod:productivebees (incompatible), mod:jei, mod:prefab (incompatible), mod:voxelmap (incompatible), mod:forge (incompatible), mod:forgeendertech, mod:collective, mod:corpse, mod:travelersbackpack (incompatible), mod:elementalmastery (incompatible), mod:villagespawnpoint, mod:adfinders, mod:quickhomes (incompatible), mod:nccreepers, mod:healthoverlay, mod:golems (incompatible), mod:ore_reeds (incompatible), mod:alllootdrops
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
	OptiFine Version: OptiFine_1.16.2_HD_U_G3_pre7
	OptiFine Build: 20200828-154435
	Render Distance Chunks: 2
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.4.0 - Build 20.19.15.4835
	OpenGlRenderer: Intel(R) HD Graphics 405
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by JaisDK** [comment]
Can you try the latest version and see if that fixes the issue? The version you are using was compiled for an earlier version of forge and they probably changed something since then. The new 0.3.2 version is for the latest forge.
